version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - save_cache:
          paths:
            - /src/node_modules
          key:  "node-packages"
      - run: npm run lint

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: 
            - "node-packages"
      - run: npm i
      - run: npm run test 

  analyze:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: 
            - "node-packages"
      - run: npm i
      - run: npm audit 
  
workflows:
  pre-deploy-workflow:
    jobs:
      - build
      - test:
          requires:
            - "build"
      - analyze:
          requires:
            - "test"  